version: '3.8'
services:
  db:
    image: mariadb
    ports:
      - 3306-3316:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db_develop:/var/lib/mysql
  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db:db
